cp -r data/anderson ../corpora
cp -r data/chesterton ../corpora
cp -r data/grimm ../corpora
cp -r data/hemingway ../corpora
cp -r data/london ../corpora
cp -r data/massQuantities ../corpora
cp -r data/ohenry ../corpora
cp -r data/wilde ../corpora
cp -r data/wodehouse ../corpora
