rm -f dataBIG/grimm/adventures_of_chanticleer_and_partlet.json
rm -f dataBIG/grimm/rumpelstiltskin.json
rm -f dataBIG/grimm/wedding_of_mrs_fox.json
rm -f dataBIG/lovecraft/at_the_mountains_of_madness.json
rm -f dataBIG/lovecraft/cool_air.json
rm -f dataBIG/lovecraft/the_call_of_cthulhu.json
rm -f dataBIG/lovecraft/the_case_of_charles_dexter_ward.json
rm -f dataBIG/lovecraft/the_colour_out_of_space.json
rm -f dataBIG/lovecraft/the_dunwich_horror.json
rm -f dataBIG/lovecraft/the_festival.json
rm -f dataBIG/lovecraft/the_haunter_of_the_dark.json
rm -f dataBIG/lovecraft/the_horror_at_red_hook.json
rm -f dataBIG/lovecraft/the_lurking_fear.json
rm -f dataBIG/lovecraft/the_quest_of_iranon.json
rm -f dataBIG/lovecraft/the_shadow_over_innsmouth.json
rm -f dataBIG/lovecraft/the_shunned_house.json
rm -f dataBIG/lovecraft/the_silver_key.json
rm -f dataBIG/lovecraft/the_thing_on_the_doorstep.json
rm -f dataBIG/lovecraft/through_the_gates_of_the_silver_key.json
rm -f dataBIG/mass_quantities/a_bad_day_for_sales__leiber.json
rm -f dataBIG/mass_quantities/a_good_woman__bromfield.json
rm -f dataBIG/mass_quantities/a_matter_of_protocol__sharkey.json
rm -f dataBIG/mass_quantities/a_modern_aladdin_or_the_wonderful_adventures_of_ol__pyle.json
rm -f dataBIG/mass_quantities/a_positive_romance_1898__bellamy.json
rm -f dataBIG/mass_quantities/a_soldier_s_home_is_battle__stone.json
rm -f dataBIG/mass_quantities/an_imperial_lover__taylor.json
rm -f dataBIG/mass_quantities/arqtiq_a_study_of_the_marvels_at_the_north_pole__adolph.json
rm -f dataBIG/mass_quantities/at_war_with_society_or_tales_of_the_outcasts__m_levy.json
rm -f dataBIG/mass_quantities/atom_drive__fontenay.json
rm -f dataBIG/mass_quantities/bear_trap__nourse.json
rm -f dataBIG/mass_quantities/business_for_the_lawyers__robin.json
rm -f dataBIG/mass_quantities/cambridge_pieces__butler.json
rm -f dataBIG/mass_quantities/castle_rackrent__edgeworth.json
rm -f dataBIG/mass_quantities/catalysis__anderson.json
rm -f dataBIG/mass_quantities/chain_of_command__arr.json
rm -f dataBIG/mass_quantities/chalk_face__frank.json
rm -f dataBIG/mass_quantities/christ_s_journal__bartlett.json
rm -f dataBIG/mass_quantities/circle_of_confusion__smith.json
rm -f dataBIG/mass_quantities/court_netherleigh_a_novel__mrs.json
rm -f dataBIG/mass_quantities/deny_the_slake__wilson.json
rm -f dataBIG/mass_quantities/dracula_s_guest__stoker.json
rm -f dataBIG/mass_quantities/esther__adams.json
rm -f dataBIG/mass_quantities/fine_feathers__smith.json
rm -f dataBIG/mass_quantities/fire_worship_from_mosses_from_an_old_manse__hawthorne.json
rm -f dataBIG/mass_quantities/flower_and_jewel_or_daisy_forrest_s_daughter__mrs.json
rm -f dataBIG/mass_quantities/for_the_love_of_lady_margaret_a_romance_of_the_los__wilson.json
rm -f dataBIG/mass_quantities/gettysburg_stories_of_the_red_harvest_and_the_afte__singmaster.json
rm -f dataBIG/mass_quantities/glow_worm__ellison.json
rm -f dataBIG/mass_quantities/going_into_society__dickens.json
rm -f dataBIG/mass_quantities/hagerty_s_enzymes__haley.json
rm -f dataBIG/mass_quantities/has_anyone_here_seen_kelly__walton.json
rm -f dataBIG/mass_quantities/hellflower__smith.json
rm -f dataBIG/mass_quantities/hellhounds_of_the_cosmos__simak.json
rm -f dataBIG/mass_quantities/her_country__andrews.json
rm -f dataBIG/mass_quantities/his_brother_s_keeper__tuttle.json
rm -f dataBIG/mass_quantities/hostage_a_terran_empire_story__wilson.json
rm -f dataBIG/mass_quantities/ice_planet__selwyn.json
rm -f dataBIG/mass_quantities/idealia_a_utopian_dream_or_resthaven__thompson.json
rm -f dataBIG/mass_quantities/in_the_clutch_of_the_war_god__hastings.json
rm -f dataBIG/mass_quantities/iron_hand_chief_of_the_tory_league_or_the_double_f__forest.json
rm -f dataBIG/mass_quantities/jinx_ship_to_the_rescue__coppel.json
rm -f dataBIG/mass_quantities/jock_s_inheritance__le_feuvre.json
rm -f dataBIG/mass_quantities/jules_of_the_great_heart_b_free_trapper_and_outlaw__mott.json
rm -f dataBIG/mass_quantities/kiana_a_tradition_of_hawaii__jarves.json
rm -f dataBIG/mass_quantities/la_mere_bauche_from_tales_of_all_countries__trollope.json
rm -f dataBIG/mass_quantities/lalla_rookh_b_an_oriental_romance__moore.json
rm -f dataBIG/mass_quantities/landscape_with_figures__fraser.json
rm -f dataBIG/mass_quantities/legend__dane.json
rm -f dataBIG/mass_quantities/let_s_get_together__asimov.json
rm -f dataBIG/mass_quantities/life_and_death_of_mr_badman__bunyan.json
rm -f dataBIG/mass_quantities/listen_children_listen__west.json
rm -f dataBIG/mass_quantities/lolly_willowes_b_or_the_loving_huntsman__warner.json
rm -f dataBIG/mass_quantities/man_s_best_friend__smith.json
rm -f dataBIG/mass_quantities/meddler_s_moon__smith.json
rm -f dataBIG/mass_quantities/medusa_s_coil__bishop_lovecraft.json
rm -f dataBIG/mass_quantities/milk_run__locke.json
rm -f dataBIG/mass_quantities/modus_vivendi__berryman.json
rm -f dataBIG/mass_quantities/monopoly__phillips_roberts.json
rm -f dataBIG/mass_quantities/mr_bamboo_and_the_honorable_little_god_a_christmas__little.json
rm -f dataBIG/mass_quantities/murder_in_black_letter__anderson.json
rm -f dataBIG/mass_quantities/nice_girl_with_5_husbands__leiber.json
rm -f dataBIG/mass_quantities/obil_keeper_of_camels_b_being_the_parable_of_the_m__bell.json
rm -f dataBIG/mass_quantities/off_the_beam__smith.json
rm -f dataBIG/mass_quantities/on_the_plains_with_custer_the_western_life_and_dee__sabin.json
rm -f dataBIG/mass_quantities/p_laski_s_tunament_1891__page.json
rm -f dataBIG/mass_quantities/pakia_1901__becke.json
rm -f dataBIG/mass_quantities/planet_of_sand__leinster.json
rm -f dataBIG/mass_quantities/possession_b_a_novel__bromfield.json
rm -f dataBIG/mass_quantities/reinstern__richberg.json
rm -f dataBIG/mass_quantities/resurrection_seven__marlowe.json
rm -f dataBIG/mass_quantities/rip_van_winkle__irving.json
rm -f dataBIG/mass_quantities/rockabye_grady__mason.json
rm -f dataBIG/mass_quantities/rose_a_charlitte__saunders.json
rm -f dataBIG/mass_quantities/rough_beast__aycock.json
rm -f dataBIG/mass_quantities/round_the_fire_stories__doyle.json
rm -f dataBIG/mass_quantities/sappho_s_journal__bartlett.json
rm -f dataBIG/mass_quantities/selections_from_poe__poe.json
rm -f dataBIG/mass_quantities/shades_of_davy_crockett__pratt.json
rm -f dataBIG/mass_quantities/snowball__anderson.json
rm -f dataBIG/mass_quantities/spawn_of_the_venus_sea__walton.json
rm -f dataBIG/mass_quantities/status_quo__reynolds.json
rm -f dataBIG/mass_quantities/stern__friedman.json
rm -f dataBIG/mass_quantities/sweet_tooth__young.json
rm -f dataBIG/mass_quantities/task_to_luna__coppel.json
rm -f dataBIG/mass_quantities/tea_tray_in_the_sky__smith.json
rm -f dataBIG/mass_quantities/tepondicon__jacobi.json
rm -f dataBIG/mass_quantities/the_1st__ludwig.json
rm -f dataBIG/mass_quantities/the_adventures_of_a_black_coat_b_containing_a_seri__anonymous.json
rm -f dataBIG/mass_quantities/the_air_of_castor_oil__harmon.json
rm -f dataBIG/mass_quantities/the_alien__jones.json
rm -f dataBIG/mass_quantities/the_bar_20_3__mulford.json
rm -f dataBIG/mass_quantities/the_beauty_of_the_village__mitford.json
rm -f dataBIG/mass_quantities/the_boy_ranger_or_the_heiress_of_the_golden_horn__coomes.json
rm -f dataBIG/mass_quantities/the_call_of_the_south__durham.json
rm -f dataBIG/mass_quantities/the_continental_dragoon_a_love_story_of_philipse_m__stephens.json
rm -f dataBIG/mass_quantities/the_cybernetic_kid__jakes.json
rm -f dataBIG/mass_quantities/the_description_of_a_new_world_called_the_blazing__of.json
rm -f dataBIG/mass_quantities/the_draw__bixby.json
rm -f dataBIG/mass_quantities/the_end_how_the_great_war_was_stopped_a_novelistic__gratacap.json
rm -f dataBIG/mass_quantities/the_evil_guest__le_fanu.json
rm -f dataBIG/mass_quantities/the_executioner__riley.json
rm -f dataBIG/mass_quantities/the_fixer__smith.json
rm -f dataBIG/mass_quantities/the_forerunners__arkawy_henig.json
rm -f dataBIG/mass_quantities/the_ghost_in_the_tower_an_episode_in_jacobia__reed.json
rm -f dataBIG/mass_quantities/the_gift__sturgis.json
rm -f dataBIG/mass_quantities/the_giftie_gien__jameson.json
rm -f dataBIG/mass_quantities/the_girl_at_silver_thistle__hale.json
rm -f dataBIG/mass_quantities/the_golgotha_dancers__wellman.json
rm -f dataBIG/mass_quantities/the_good_work__thomas.json
rm -f dataBIG/mass_quantities/the_gostak_and_the_doshes__breuer.json
rm -f dataBIG/mass_quantities/the_grave_of_solon_regh__stearns.json
rm -f dataBIG/mass_quantities/the_gravity_business__gunn.json
rm -f dataBIG/mass_quantities/the_hills_of_the_dead__howard.json
rm -f dataBIG/mass_quantities/the_holly_tree__dickens.json
rm -f dataBIG/mass_quantities/the_house_of_quiet_an_autobiography__benson.json
rm -f dataBIG/mass_quantities/the_hyborian_age__howard.json
rm -f dataBIG/mass_quantities/the_last_letter__leiber.json
rm -f dataBIG/mass_quantities/the_last_quarry__walton.json
rm -f dataBIG/mass_quantities/the_lead_of_honour__richardson.json
rm -f dataBIG/mass_quantities/the_magnificent_possession__asimov.json
rm -f dataBIG/mass_quantities/the_magnificent_profession__thomas.json
rm -f dataBIG/mass_quantities/the_man_who_had_spiders__aycock.json
rm -f dataBIG/mass_quantities/the_marooner__stearns.json
rm -f dataBIG/mass_quantities/the_marrying_man__farrell.json
rm -f dataBIG/mass_quantities/the_mating_of_the_moons__walton.json
rm -f dataBIG/mass_quantities/the_messengers__davis.json
rm -f dataBIG/mass_quantities/the_monk_and_the_hangman_s_daughter__bierce_danziger_voss.json
rm -f dataBIG/mass_quantities/the_moon_of_skulls__howard.json
rm -f dataBIG/mass_quantities/the_painted_room__wilson.json
rm -f dataBIG/mass_quantities/the_patriot__fontenay.json
rm -f dataBIG/mass_quantities/the_penultimate_trump__ettinger.json
rm -f dataBIG/mass_quantities/the_pilot_and_the_bushman__jacobs.json
rm -f dataBIG/mass_quantities/the_planet_savers__bradley.json
rm -f dataBIG/mass_quantities/the_purple_cloud__shiel.json
rm -f dataBIG/mass_quantities/the_push_of_a_finger__bester.json
rm -f dataBIG/mass_quantities/the_putnam_tradition__dorman.json
rm -f dataBIG/mass_quantities/the_radio_ghost__kline.json
rm -f dataBIG/mass_quantities/the_raider__berry.json
rm -f dataBIG/mass_quantities/the_red_brain__wandrei.json
rm -f dataBIG/mass_quantities/the_right_side_of_the_tracks__teichner.json
rm -f dataBIG/mass_quantities/the_seven_vagabonds_from_twice_told_tales__hawthorne.json
rm -f dataBIG/mass_quantities/the_storm_of_london_a_social_rhapsody__blaze.json
rm -f dataBIG/mass_quantities/the_ties_that_bind__miller.json
rm -f dataBIG/mass_quantities/the_u_p_trail__grey.json
rm -f dataBIG/mass_quantities/the_unforgiving_offender__scott.json
rm -f dataBIG/mass_quantities/the_used_people_lot__fang.json
rm -f dataBIG/mass_quantities/the_web_of_time__knowles.json
rm -f dataBIG/mass_quantities/the_wonderful_year__locke.json
rm -f dataBIG/mass_quantities/through_one_administration__burnett.json
rm -f dataBIG/mass_quantities/through_the_sun_in_an_airship__mastin.json
rm -f dataBIG/mass_quantities/tickets_to_paradise__james.json
rm -f dataBIG/mass_quantities/touch_the_sky__coppel.json
rm -f dataBIG/mass_quantities/traders_risk__aycock.json
rm -f dataBIG/mass_quantities/wait_for_weight__mckenty.json
rm -f dataBIG/mass_quantities/welcome_to_paradise__donnelson.json
rm -f dataBIG/mass_quantities/west_o_mars__fontenay.json
rm -f dataBIG/mass_quantities/when_the_owl_cries__bartlett.json
rm -f dataBIG/mass_quantities/when_time_rolled_back__repp.json
rm -f dataBIG/mass_quantities/woman_s_world__silverberg.json
rm -f dataBIG/mass_quantities/young_man_from_elsewhen__jacobs.json
rm -f dataBIG/mass_quantities/youngling_a_terran_empire_story__wilson.json
rm -f dataBIG/mass_quantities/zero_hour__blade.json
rm -f dataBIG/mass_quantities/zeta_exchange_a_terran_empire_story__wilson.json
rm -f dataBIG/sherlock/noble_bachelor.json
rm -f dataBIG/sherlock/scandal_in_bohemia.json
rm -f dataBIG/wodehouse/mixer.json
