#!/usr/bin/env bash
set -euo pipefail

# Test LCATS via Python's unittest module
echo "Testing lcats ..."
set -x

python -m unittest discover -s tests -p "*_test.py"

# Turn off logging and print a blank line
{ set +x; } 2>/dev/null
echo
